# Generated by Django 5.1.6 on 2025-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Photography', 'Photography'), ('Digital Art', 'Digital Art'), ('Mixed Media', 'Mixed Media'), ('Printmaking', 'Printmaking'), ('Textile Art', 'Textile Art'), ('Performance Art', 'Performance Art'), ('Installation', 'Installation'), ('Drawing', 'Drawing'), ('Collage', 'Collage'), ('Street Art', 'Street Art'), ('Ceramics', 'Ceramics'), ('Glass Art', 'Glass Art'), ('Metalwork', 'Metalwork'), ('Woodworking', 'Woodworking'), ('Conceptual Art', 'Conceptual Art'), ('Contemporary Art', 'Contemporary Art'), ('Abstract Art', 'Abstract Art'), ('Classical Art', 'Classical Art'), ('Figurative Art', 'Figurative Art'), ('Land Art', 'Land Art'), ('Film & Video Art', 'Film & Video Art'), ('Graphic Design', 'Graphic Design'), ('Illustration', 'Illustration'), ('Animation', 'Animation'), ('Virtual Art', 'Virtual Art'), ('Photography (Fine Art)', 'Photography (Fine Art)'), ('Environmental Art', 'Environmental Art'), ('Social Practice', 'Social Practice'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
