# Generated by Django 5.1.6 on 2025-02-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
