# Generated by Django 5.1.6 on 2025-02-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
